server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: productserver
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/product_schema?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        logging.level:
#        org.hibernate.SQL: debug
        #        org.hibernate.type: trace
#  data:
#    mongodb:
#      uri:
  # OAuth
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ffff43456dc6c817e9c170c889116ea1
#            client-secret: 9sUohDxFqvuLBt4za5EviV9p1pk12NWn
#            #            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            redirect-uri: https://i10a810.p.ssafy.io/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_post
#            client-name: Kakao
#            scope:
#              - profile_nickname
#              - profile_image
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id


logging.level:
  org.hibernate.SQL: info
  org.hibernate.type: info
  com.netflix: WARN
  org.springframework.web: WARN
  com.example: DEBUG
#  org.springframework.security: info

#classhub:
#  react:
#    #    domain: "http://localhost:5173"
#    domain: "https://i10a810.p.ssafy.io"

#key:
#  jwt:
#    secret: CuBcynyOndQHCzQPatvFLkdyndtYIrysJKUPCHRMETNKSPxbhQ
